basePath: /
definitions:
  models.ServiceCall:
    properties:
      call_time:
        type: string
      cost:
        type: integer
      metadata:
        additionalProperties: {}
        type: object
      model_id:
        type: string
      request_id:
        type: string
      status:
        type: string
      user_id:
        type: string
    type: object
host: localhost:3002
info:
  contact: {}
  description: API server for NeuralService Application
  title: NeuralService API
  version: "1.0"
paths:
  /calls:
    get:
      description: Get call information
      operationId: get-call
      parameters:
      - description: User ID
        in: query
        name: user
        type: string
      - description: Model ID
        in: query
        name: model
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            items:
              $ref: '#/definitions/models.ServiceCall'
            type: array
        "400":
          description: Bad Request
      summary: GetCall
      tags:
      - get
    post:
      consumes:
      - application/json
      description: Store call information
      operationId: store-call
      parameters:
      - description: call info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.ServiceCall'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: StoreCall
      tags:
      - store
swagger: "2.0"
